"""Regression matrices for the default Large and Small display rotations."""

import json
from pathlib import Path

import pytest

from schedule import build_scheduler

ROOT = Path(__file__).resolve().parents[1]

# Cycle 1 contains every enabled base: alternates must not replace base screens.
EXPECTED_STARTUP = ['date',
 'on this day',
 'adsb stats',
 'adsb live',
 'news headlines',
 'vrnof',
 'weather1',
 'weather2',
 'air quality',
 'weather alert',
 'weather hourly',
 'weather daily',
 'astronomical',
 'weather quad',
 'weather radar',
 'inside',
 'bears logo',
 'bears next',
 'NFL Scoreboard',
 'NFL Overview NFC',
 'NFL Overview AFC',
 'hawks logo',
 'hawks last',
 'hawks live',
 'hawks next',
 'hawks next home',
 'hawks schedule quad',
 'NHL Scoreboard',
 'cubs logo',
 'cubs stand3',
 'cubs last',
 'cubs live',
 'cubs next',
 'cubs next home',
 'cubs current series',
 'cubs next series',
 'cubs next home series',
 'cubs schedule quad',
 'sox logo',
 'sox stand3',
 'sox last',
 'sox live',
 'sox next',
 'sox next home',
 'sox current series',
 'sox next series',
 'sox next home series',
 'sox schedule quad',
 'MLB Scoreboard',
 'NL Overview+WC',
 'AL Overview+WC']

# Normal rotations transcribed as ordered rows from the approved scheduling matrix.
# Keeping every row explicit makes a changed default produce a useful list diff.
EXPECTED_NORMAL_PASSES = {1: ['date',
     'news headlines',
     'weather1',
     'weather2',
     'weather alert',
     'weather hourly',
     'weather quad',
     'weather radar',
     'inside',
     'cubs live',
     'sox live'],
 2: ['date',
     'news headlines 2',
     'weather1',
     'weather2',
     'air quality',
     'weather alert',
     'weather hourly',
     'astronomical',
     'weather quad',
     'weather radar',
     'inside',
     'NFL Scoreboard',
     'hawks logo',
     'hawks last',
     'hawks live',
     'hawks next',
     'hawks next home',
     'hawks schedule quad',
     'NHL Scoreboard',
     'cubs logo',
     'cubs stand3',
     'cubs last',
     'cubs live',
     'cubs schedule quad',
     'sox live',
     'MLB Scoreboard',
     'NL Overview+WC',
     'AL Overview+WC'],
 3: ['nixie',
     'adsb stats',
     'adsb live',
     'news headlines',
     'vrnof',
     'weather1',
     'weather2',
     'weather alert',
     'weather hourly',
     'weather daily',
     'weather quad',
     'weather radar',
     'inside',
     'bears logo',
     'bears next',
     'cubs live',
     'cubs next',
     'cubs next home',
     'cubs current series',
     'cubs next series',
     'cubs next home series',
     'sox live'],
 4: ['date',
     'news headlines 2',
     'weather1',
     'weather2',
     'air quality',
     'weather alert',
     'weather hourly',
     'astronomical',
     'weather quad',
     'weather radar',
     'inside',
     'NFL Scoreboard',
     'NFL Overview NFC',
     'NFL Overview AFC',
     'hawks logo',
     'hawks last',
     'hawks live',
     'hawks next',
     'hawks next home',
     'hawks schedule quad',
     'NHL Scoreboard',
     'cubs logo',
     'cubs stand3',
     'cubs last',
     'cubs live',
     'cubs schedule quad',
     'sox live',
     'MLB Scoreboard',
     'NL Overview+WC',
     'AL Overview+WC'],
 5: ['date',
     'news headlines',
     'weather1',
     'weather2',
     'weather alert',
     'weather hourly',
     'weather quad',
     'weather radar',
     'inside',
     'cubs live',
     'sox logo',
     'sox stand3',
     'sox last',
     'sox live',
     'sox schedule quad'],
 6: ['nixie',
     'on this day',
     'adsb stats',
     'adsb live',
     'news headlines 2',
     'vrnof',
     'weather1',
     'weather2',
     'air quality',
     'weather alert',
     'weather hourly',
     'weather daily',
     'astronomical',
     'weather quad',
     'weather radar',
     'inside',
     'bears logo',
     'bears next',
     'NFL Scoreboard',
     'hawks logo',
     'hawks last',
     'hawks live',
     'hawks next',
     'hawks next home',
     'hawks schedule quad',
     'NHL Scoreboard',
     'cubs logo',
     'cubs stand3',
     'cubs last',
     'cubs live',
     'cubs next',
     'cubs next home',
     'cubs current series',
     'cubs next series',
     'cubs next home series',
     'cubs schedule quad',
     'sox live',
     'MLB Scoreboard',
     'NL Overview+WC',
     'AL Overview+WC'],
 7: ['date',
     'news headlines',
     'weather1',
     'weather2',
     'weather alert',
     'weather hourly',
     'weather quad',
     'weather radar',
     'inside',
     'cubs live',
     'sox live',
     'sox next',
     'sox next home',
     'sox current series',
     'sox next series',
     'sox next home series'],
 8: ['date',
     'news headlines 2',
     'weather1',
     'weather2',
     'air quality',
     'weather alert',
     'weather hourly',
     'astronomical',
     'weather quad',
     'weather radar',
     'inside',
     'NFL Scoreboard',
     'NFL Overview NFC',
     'NFL Overview AFC',
     'hawks logo',
     'hawks last',
     'hawks live',
     'hawks next',
     'hawks next home',
     'hawks schedule quad',
     'NHL Scoreboard',
     'cubs logo',
     'cubs stand3',
     'cubs last',
     'cubs live',
     'cubs schedule quad',
     'sox live',
     'MLB Scoreboard',
     'MLB NL Standings',
     'MLB AL Standings'],
 9: ['nixie',
     'adsb stats',
     'adsb live',
     'news headlines',
     'vrnof',
     'weather1',
     'weather2',
     'weather alert',
     'weather hourly',
     'weather daily',
     'weather quad',
     'weather radar',
     'inside',
     'bears logo',
     'bears next',
     'cubs live',
     'cubs next',
     'cubs next home',
     'cubs current series',
     'cubs next series',
     'cubs next home series',
     'sox live'],
 10: ['date',
      'news headlines 2',
      'weather1',
      'weather2',
      'air quality',
      'weather alert',
      'weather hourly',
      'astronomical',
      'weather quad',
      'weather radar',
      'inside',
      'NFL Scoreboard',
      'hawks logo',
      'hawks last',
      'hawks live',
      'hawks next',
      'hawks next home',
      'hawks schedule quad',
      'NHL Scoreboard',
      'cubs logo',
      'cubs stand3',
      'cubs last',
      'cubs live',
      'cubs schedule quad',
      'sox logo',
      'sox stand3',
      'sox last',
      'sox live',
      'sox schedule quad',
      'MLB Scoreboard',
      'NL Overview+WC',
      'AL Overview+WC'],
 11: ['date',
      'news headlines',
      'weather1',
      'weather2',
      'weather alert',
      'weather hourly',
      'weather quad',
      'weather radar',
      'inside',
      'cubs live',
      'sox live'],
 12: ['nixie',
      'on this day',
      'adsb stats',
      'adsb live',
      'news headlines 2',
      'vrnof',
      'weather1',
      'weather2',
      'air quality',
      'weather alert',
      'weather hourly',
      'weather daily',
      'astronomical',
      'weather quad',
      'weather radar',
      'inside',
      'bears logo',
      'bears next',
      'NFL Scoreboard',
      'NFL Standings NFC',
      'NFL Standings AFC',
      'hawks logo',
      'hawks last',
      'hawks live',
      'hawks next',
      'hawks next home',
      'hawks schedule quad',
      'NHL Scoreboard',
      'cubs logo',
      'cubs stand3',
      'cubs last',
      'cubs live',
      'cubs next',
      'cubs next home',
      'cubs current series',
      'cubs next series',
      'cubs next home series',
      'cubs schedule quad',
      'sox live',
      'MLB Scoreboard',
      'NL Overview+WC',
      'AL Overview+WC']}


SMALL_EXPECTED_STARTUP = [
    "date",
    "weather1",
    "weather2",
    "air quality",
    "weather alert",
    "weather hourly",
    "weather daily",
    "weather radar",
    "astronomical",
    "inside",
    "news headlines",
    "vrnof",
    "hawks logo",
    "hawks last",
    "hawks next",
    "hawks next home",
    "cubs logo",
    "cubs stand3",
    "cubs last",
    "cubs live",
    "cubs next",
    "cubs next home",
    "cubs current series",
    "cubs next series",
    "cubs next home series",
    "cubs schedule quad",
    "sox logo",
    "sox stand3",
    "sox last",
    "sox live",
    "sox next",
    "sox next home",
    "sox current series",
    "sox next series",
    "sox next home series",
    "sox schedule quad",
    "MLB Scoreboard",
    "NL Overview+WC",
    "AL Overview+WC",
    "bears logo",
    "bears next",
    "NFL Scoreboard",
    "NFL Overview NFC",
    "NFL Overview AFC",
    "on this day",
    "adsb stats",
    "adsb live",
]

SMALL_EXPECTED_NORMAL_PASSES = {
    1: [
        "date",
        "weather1",
        "weather2",
        "air quality",
        "weather alert",
        "weather hourly",
        "weather daily",
        "weather radar",
        "inside",
        "news headlines",
        "hawks logo",
        "hawks last",
        "hawks next",
        "hawks next home",
        "cubs live",
        "sox live",
    ],
    2: [
        "date",
        "weather1",
        "weather2",
        "air quality",
        "weather alert",
        "weather hourly",
        "weather daily",
        "weather radar",
        "astronomical",
        "inside",
        "news headlines 2",
        "hawks logo",
        "hawks last",
        "hawks next",
        "hawks next home",
        "cubs logo",
        "cubs stand3",
        "cubs last",
        "cubs live",
        "cubs schedule quad",
        "sox live",
        "MLB Scoreboard",
        "NL Overview+WC",
        "AL Overview+WC",
        "NFL Scoreboard",
    ],
    3: [
        "date",
        "weather1",
        "weather2",
        "air quality",
        "weather alert",
        "weather hourly",
        "weather daily",
        "weather radar",
        "inside",
        "news headlines",
        "vrnof",
        "hawks logo",
        "hawks last",
        "hawks next",
        "hawks next home",
        "cubs live",
        "cubs next",
        "cubs next home",
        "cubs current series",
        "cubs next series",
        "cubs next home series",
        "sox live",
        "bears logo",
        "bears next",
        "adsb stats",
        "adsb live",
    ],
    4: [
        "date",
        "weather1",
        "weather2",
        "air quality",
        "weather alert",
        "weather hourly",
        "weather daily",
        "weather radar",
        "astronomical",
        "inside",
        "news headlines 2",
        "hawks logo",
        "hawks last",
        "hawks next",
        "hawks next home",
        "cubs logo",
        "cubs stand3",
        "cubs last",
        "cubs live",
        "cubs schedule quad",
        "sox live",
        "MLB Scoreboard",
        "NL Overview+WC",
        "AL Overview+WC",
        "NFL Scoreboard",
        "NFL Overview NFC",
        "NFL Overview AFC",
    ],
    5: [
        "date",
        "weather1",
        "weather2",
        "air quality",
        "weather alert",
        "weather hourly",
        "weather daily",
        "weather radar",
        "inside",
        "news headlines",
        "hawks logo",
        "hawks last",
        "hawks next",
        "hawks next home",
        "cubs live",
        "sox logo",
        "sox stand3",
        "sox last",
        "sox live",
        "sox schedule quad",
    ],
    6: [
        "date",
        "weather1",
        "weather2",
        "air quality",
        "weather alert",
        "weather hourly",
        "weather daily",
        "weather radar",
        "astronomical",
        "inside",
        "news headlines 2",
        "vrnof",
        "hawks logo",
        "hawks last",
        "hawks next",
        "hawks next home",
        "cubs logo",
        "cubs stand3",
        "cubs last",
        "cubs live",
        "cubs next",
        "cubs next home",
        "cubs current series",
        "cubs next series",
        "cubs next home series",
        "cubs schedule quad",
        "sox live",
        "MLB Scoreboard",
        "NL Overview+WC",
        "AL Overview+WC",
        "bears logo",
        "bears next",
        "NFL Scoreboard",
        "on this day",
        "adsb stats",
        "adsb live",
    ],
    7: [
        "date",
        "weather1",
        "weather2",
        "air quality",
        "weather alert",
        "weather hourly",
        "weather daily",
        "weather radar",
        "inside",
        "news headlines",
        "hawks logo",
        "hawks last",
        "hawks next",
        "hawks next home",
        "cubs live",
        "sox live",
        "sox next",
        "sox next home",
        "sox current series",
        "sox next series",
        "sox next home series",
    ],
    8: [
        "date",
        "weather1",
        "weather2",
        "air quality",
        "weather alert",
        "weather hourly",
        "weather daily",
        "weather radar",
        "astronomical",
        "inside",
        "news headlines 2",
        "hawks logo",
        "hawks last",
        "hawks next",
        "hawks next home",
        "cubs logo",
        "cubs stand3",
        "cubs last",
        "cubs live",
        "cubs schedule quad",
        "sox live",
        "MLB Scoreboard",
        "MLB NL Standings",
        "MLB AL Standings",
        "NFL Scoreboard",
        "NFL Overview NFC",
        "NFL Overview AFC",
    ],
    9: [
        "date",
        "weather1",
        "weather2",
        "air quality",
        "weather alert",
        "weather hourly",
        "weather daily",
        "weather radar",
        "inside",
        "news headlines",
        "vrnof",
        "hawks logo",
        "hawks last",
        "hawks next",
        "hawks next home",
        "cubs live",
        "cubs next",
        "cubs next home",
        "cubs current series",
        "cubs next series",
        "cubs next home series",
        "sox live",
        "bears logo",
        "bears next",
        "adsb stats",
        "adsb live",
    ],
    10: [
        "date",
        "weather1",
        "weather2",
        "air quality",
        "weather alert",
        "weather hourly",
        "weather daily",
        "weather radar",
        "astronomical",
        "inside",
        "news headlines 2",
        "hawks logo",
        "hawks last",
        "hawks next",
        "hawks next home",
        "cubs logo",
        "cubs stand3",
        "cubs last",
        "cubs live",
        "cubs schedule quad",
        "sox logo",
        "sox stand3",
        "sox last",
        "sox live",
        "sox schedule quad",
        "MLB Scoreboard",
        "NL Overview+WC",
        "AL Overview+WC",
        "NFL Scoreboard",
    ],
    11: [
        "date",
        "weather1",
        "weather2",
        "air quality",
        "weather alert",
        "weather hourly",
        "weather daily",
        "weather radar",
        "inside",
        "news headlines",
        "hawks logo",
        "hawks last",
        "hawks next",
        "hawks next home",
        "cubs live",
        "sox live",
    ],
    12: [
        "date",
        "weather1",
        "weather2",
        "air quality",
        "weather alert",
        "weather hourly",
        "weather daily",
        "weather radar",
        "astronomical",
        "inside",
        "news headlines 2",
        "vrnof",
        "hawks logo",
        "hawks last",
        "hawks next",
        "hawks next home",
        "cubs logo",
        "cubs stand3",
        "cubs last",
        "cubs live",
        "cubs next",
        "cubs next home",
        "cubs current series",
        "cubs next series",
        "cubs next home series",
        "cubs schedule quad",
        "sox live",
        "MLB Scoreboard",
        "NL Overview+WC",
        "AL Overview+WC",
        "bears logo",
        "bears next",
        "NFL Scoreboard",
        "NFL Standings NFC",
        "NFL Standings AFC",
        "on this day",
        "adsb stats",
        "adsb live",
    ],
}


def _large_config() -> dict:
    with (ROOT / "default_screens_large.json").open(encoding="utf-8") as config_file:
        return json.load(config_file)["config"]


def _frequency(spec: object) -> int:
    if isinstance(spec, dict):
        return int(spec["frequency"])
    return int(spec)


def _resolved_config_page_order(config: dict) -> list[str]:
    """Resolve Ungrouped then sequenced playlists, like the config page/scheduler."""
    screens = config["screens"]
    playlists = config["playlists"]
    playlist_ids = [item["playlist"] for item in config["sequence"]]
    playlist_ids.extend(playlist_id for playlist_id in playlists if playlist_id not in playlist_ids)

    assignment = {}
    for playlist_id in playlist_ids:
        for step in playlists[playlist_id]["steps"]:
            screen_id = step["screen"]
            if screen_id in screens:
                assignment.setdefault(screen_id, playlist_id)

    return [
        screen_id
        for group_id in [None, *playlist_ids]
        for screen_id in screens
        if assignment.get(screen_id) == group_id
    ]


def _small_config() -> dict:
    with (ROOT / "default_screens_small.json").open(encoding="utf-8") as config_file:
        return json.load(config_file)["config"]


def _custom_device_config() -> dict:
    return {
        "screens": {
            "date": {"frequency": 2},
            "inside": {"frequency": 3},
            "weather1": {"frequency": 0},
            "weather2": {"frequency": 1},
        },
        "playlists": {
            "custom": {"steps": [{"screen": "inside"}, {"screen": "date"}]}
        },
        "sequence": [{"playlist": "custom"}],
    }


@pytest.mark.parametrize(
    "config_factory",
    [_large_config, _small_config, _custom_device_config],
    ids=["large-default", "small-default", "custom-device"],
)
def test_rotation_matrix_uses_cycle_one_offset_for_every_configuration(config_factory):
    config = config_factory()
    screens = config["screens"]
    resolved_order = _resolved_config_page_order(config)
    enabled_order = [
        screen_id for screen_id in resolved_order if _frequency(screens[screen_id]) > 0
    ]
    entries = build_scheduler(config).preview_scheduled_entries(2_000)
    matrix = {
        cycle: [entry.screen_id for entry in entries if entry.cycle_number == cycle]
        for cycle in range(1, 14)
    }

    # Cycle 1 is the initial, ordinary cycle and always contains every enabled base.
    assert matrix[1] == enabled_order
    assert all(entry.cycle_number >= 1 for entry in entries)

    for cycle in range(2, 14):
        expected_bases = [
            screen_id
            for screen_id in enabled_order
            if (cycle - 1) % _frequency(screens[screen_id]) == 0
        ]
        actual = matrix[cycle]
        assert len(actual) == len(expected_bases)
        for played_id, base_id in zip(actual, expected_bases, strict=True):
            spec = screens[base_id]
            allowed = {base_id}
            if isinstance(spec, dict) and isinstance(spec.get("alt"), dict):
                alternate = spec["alt"]["screen"]
                allowed.update(alternate if isinstance(alternate, list) else [alternate])
            assert played_id in allowed


@pytest.mark.parametrize("frequency", [1, 2, 3, 6])
def test_custom_device_frequency_occurs_on_one_plus_multiples(frequency):
    config = {"screens": {"date": frequency}}
    entries = build_scheduler(config).preview_scheduled_entries(4)

    assert [entry.cycle_number for entry in entries] == [
        1 + frequency * multiplier for multiplier in range(4)
    ]


def test_frequency_zero_is_not_an_independent_custom_device_screen():
    config = _custom_device_config()
    entries = build_scheduler(config).preview_scheduled_entries(30)

    assert "weather1" not in [entry.screen_id for entry in entries]
